apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baton-okta.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  okta-api-token: {{ .Values.okta.apiToken | b64enc }}
  okta-domain: {{ .Values.okta.domain | b64enc }}
  s3-file-uri: {{ .Values.s3.fileUri | b64enc }}
